# Generated by Django 3.2 on 2021-04-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.profile'),
        ),
    ]
