# Generated by Django 3.2 on 2021-04-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210424_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='', max_length=50, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
